sysapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('cadastrar/', views.cadastrar_usuario, name='cadastrar_usuario'),
    path('accounts/login/', views.fazer_login, name='fazer_login'),
    path('abrirchamado/', views.abrir_chamados, name='abrir_chamados'),
    path('logout/', auth_views.LogoutView.as_view(next_page='fazer_login'), name='logout'),
    path('dashboard/chamados/<str:estado>/', views.dashboard_chamados, name='dashboard_chamados'),

]

syscontrol/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sysapp.urls')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sysapp/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin


class UsuarioManager(BaseUserManager):
    def create_user(self, matricula, password=None, siape=None, **extra_fields):
        if not matricula and not siape:
            raise ValueError('Matrícula ou SIAPE devem ser fornecidos')

        user = self.model(matricula=matricula, siape=siape, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, matricula, password=None, siape=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(matricula, password, siape, **extra_fields)

class Usuario(AbstractBaseUser, PermissionsMixin):
    USUARIO_CHOICES = [
        ('Servidor', 'Servidor'),
        ('Aluno', 'Aluno'),
    ]
    matricula = models.CharField(unique=True, max_length=50, blank=False, null=False, verbose_name='Matrícula')
    siape = models.CharField(unique=True, max_length=50, blank=True, null=True, verbose_name='SIAPE')
    nome = models.CharField(max_length=100, blank=False, null=False, verbose_name='Nome')
    sobrenome = models.CharField(max_length=100, blank=False, null=False, verbose_name='Sobrenome')
    nome_usuario = models.CharField(unique=True, max_length=100, blank=False, null=False, verbose_name='Nome de Usuário')
    email = models.EmailField(unique=True, verbose_name='E-mail')
    password = models.CharField(max_length=128,blank=False, null=False,verbose_name='Senha', default='')
    tipo_usuario = models.CharField(max_length=8, choices=USUARIO_CHOICES, default='1', verbose_name='Tipo de Usuário')
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UsuarioManager()

    REQUIRED_FIELDS = ['nome', 'sobrenome', 'nome_usuario', 'email']
    USERNAME_FIELD = 'matricula'

   
    def __str__(self):
        return f"{self.nome} {self.sobrenome}"


class Chamado(models.Model):
    ESTADO_CHOICES = [
        ('Novos', 'Novos'),
        ('Em andamento', 'Em andamento'),
        ('Finalizados', 'Finalizados'),
    ]
 
    TIPO_CHOICES = [
        ('Suporte', 'Suporte'),
        ('Financeiro', 'Financeiro'),
        ('Outros', 'Outros')
    ]

    CATEGORIA_CHOICES = [
        ('Informática', 'Informática'),
        ('Redes', 'Redes'),
        ('Segurança', 'Segurança'),
        ('Outros', 'Outros'),
    ]

    PRIORIDADE_CHOICES = [
        ('Baixa', 'Baixa'),
        ('Média', 'Média'),
        ('Alta', 'Alta'),
    ]
    
    codigo = models.AutoField(primary_key=True)
    tipo = models.CharField(max_length=20, null=True, blank=False, choices=TIPO_CHOICES)
    categoria = models.CharField(max_length=20, blank=True, null=True, choices=CATEGORIA_CHOICES)
    titulo = models.CharField(max_length=255, blank=True, null=True)
    descricao = models.TextField(null=True, blank=True)
    prioridade = models.CharField(max_length=10, null=True, choices=PRIORIDADE_CHOICES)
    anexo = models.FileField(upload_to='anexos/', null=True, blank=True)

    estado = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='Novos', verbose_name='Estado')

    # Adicione a chave estrangeira para associar o chamado ao usuário
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE,  null=True, blank=True)
    responsavel = models.ForeignKey(Usuario, on_delete=models.SET_NULL, null=True, related_name='chamados_responsavel')



    def __str__(self):
        return f'{self.codigo}, {self.tipo}, {self.categoria}, {self.titulo}, {self.descricao}, {self.prioridade},{self.usuario}'

sysapp/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate
from .models import Usuario, Chamado


class UsuarioForm(forms.ModelForm):
    matricula = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder': 'Matrícula'}))
    password = forms.CharField(label='Senha', widget=forms.PasswordInput)

    class Meta:
        model = Usuario
        fields = '__all__'  
  

class CustomLoginForm(AuthenticationForm):
    matricula = forms.CharField(
        label='Matrícula/Siap',
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )
    password = forms.CharField(
        label='Senha',
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['matricula'].label = 'Matrícula/Siap'

    class Meta:
        model = Usuario
        fields = ['matricula', 'password']

    def clean(self):
        matricula = self.cleaned_data.get('matricula')
        password = self.cleaned_data.get('password')

        if matricula is not None and password:
            user = authenticate(request=self.request, username=matricula, password=password)
            
            if user is None:
                raise forms.ValidationError(
                    f'Matricula ou senha incorretas. Matricula fornecida: {matricula}',
                    code='invalid_login',
                    params={'matricula': matricula},
                )
            if user is None:
                raise forms.ValidationError('Matrícula ou senha incorretas. Matrícula fornecida: {}'.format(matricula))
            
            if not user.is_active:
                raise forms.ValidationError('Este usuário está inativo.')
            
            self.user_cache = user

        return self.cleaned_data

class ChamadoForm(forms.ModelForm):
    class Meta:
        model = Chamado
        fields = ['tipo', 'categoria', 'titulo', 'descricao', 'prioridade', 'anexo']



    class Meta:
        model = Usuario
        fields = '__all__'
      

sysapp/views.py
from django.shortcuts import render, redirect
from django.db import transaction
from .forms import UsuarioForm, CustomLoginForm
from django.contrib import messages
from django.urls import reverse
from .models import Usuario, Chamado
from .forms import ChamadoForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test


def cadastrar_usuario(request):
    if request.method == 'POST':
        form = UsuarioForm(request.POST)
        if form.is_valid():
            tipo_usuario = form.cleaned_data['tipo_usuario']
            matricula = form.cleaned_data['matricula']
            password = form.cleaned_data['password']
            nome_usuario = form.cleaned_data['nome_usuario']
            email = form.cleaned_data['email']

            # Alteração para criar usuário com matrícula ou SIAPE conforme o tipo de usuário
            if tipo_usuario == 'Servidor':
                siape = form.cleaned_data['siape']
                Usuario.objects.create_user(matricula=matricula, password=password, siape=siape, nome_usuario=nome_usuario, email=email, tipo_usuario=tipo_usuario)
            else:
                Usuario.objects.create_user(matricula=matricula, password=password, nome_usuario=nome_usuario, email=email, tipo_usuario=tipo_usuario)

            messages.success(request, f'O usuário {nome_usuario} foi cadastrado com sucesso!')
            return redirect('cadastrar_usuario')
    else:
        form = UsuarioForm()

    return render(request, 'cadastrar_usuario.html', {'form': form, 'show_message': False})


def fazer_login(request):
    if request.method == 'POST':
        # Note que não estamos passando o request para o formulário aqui
        form = CustomLoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('matricula')
            password = form.cleaned_data.get('password')

            print(f"Matrícula: {username}, Senha: {password}")
            user = authenticate(request=request, username=username, password=password)
            print(f"Resultado do authenticate: {user}")

            if user is not None:
                login(request, user)
                messages.success(request, "Login foi efetuado com sucesso!")
                next_url = request.POST.get('next', None)
                if next_url:
                    return redirect(next_url)
                else:
                    return redirect('abrir_chamados')
            else:
                messages.error(request, "Credenciais inválidas. Tente novamente.")
        else:
            messages.error(request, "Formulário inválido. Verifique os campos e tente novamente.")
    else:
        form = CustomLoginForm()

    return render(request, 'fazer_login.html', {'form': form})


@login_required
def abrir_chamados(request):
    if request.method == 'POST':  
        form = ChamadoForm(request.POST, request.FILES)
        if form.is_valid():
            chamado = form.save(commit=False)
            chamado.usuario = request.user 
            chamado.save()
            messages.success(request, "Chamado criado com sucesso!")
            return redirect(reverse('dashboard_chamados', kwargs={'estado': 'novos'}))
    else:
        form = ChamadoForm()

    return render(request, 'abrir_chamados.html', {'form': form})


def dashboard_chamados(request, estado='novos'):
    if request.method == 'POST':
        # Obter dados do formulário
        codigo = request.POST.get('codigo', 0)
        tipo = request.POST.get('tipo', '')
        categoria = request.POST.get('categoria', '')
        titulo = request.POST.get('titulo', '')
        descricao = request.POST.get('descricao', '')
        prioridade = request.POST.get('prioridade', '')
        responsavel_id = request.POST.get('responsavel', '')

        # Verificar se o responsável selecionado é um Servidor Técnico
        try:
            responsavel = Usuario.objects.get(id=responsavel_id, tipo_usuario='Servidor')
        except Usuario.DoesNotExist:
            responsavel = None

        # Criar o objeto de chamado e salvar se o responsável for um Servidor válido
        if responsavel:
            chamado = Chamado(
                usuario=request.user,
                codigo=codigo,
                tipo=tipo,
                categoria=categoria,
                titulo=titulo,
                descricao=descricao,
                prioridade=prioridade,
                responsavel=responsavel,
            )
            chamado.save()

    # Obter todos os técnicos para exibição no formulário
    servidores = Usuario.objects.filter(tipo_usuario='Servidor')

    # Defina a condição para filtrar os chamados com base no estado
    if estado == 'novos':
        chamados = Chamado.objects.filter(usuario=request.user, estado='Novos')
    elif estado == 'em_andamento':
        chamados = Chamado.objects.filter(usuario=request.user, estado='Em andamento')
    elif estado == 'finalizados':
        chamados = Chamado.objects.filter(usuario=request.user, estado='Finalizados')
    else:
        # Se o estado não for reconhecido, exiba todos os chamados
        chamados = Chamado.objects.filter(usuario=request.user)

    return render(request, 'dashboard_chamados.html', {'servidores': servidores, 'chamados': chamados, 'estado_atual': estado})


@transaction.atomic
def atualizar_chamados(request):
    # Função para atualizar os chamados
    def atualizar_chamados_estado(chamados, novo_estado):
        for chamado in chamados.order_by('id')[:5]:
            chamado.estado = novo_estado
            chamado.save()

    # Obter todos os chamados em estado 'Novos' do usuário
    chamados_novos = Chamado.objects.filter(usuario=request.user, estado='Novos')

    # Verificar se há mais de 5 chamados em estado 'Novos'
    if chamados_novos.count() >= 5:
        # Atualizar os 5 chamados mais antigos para estado 'Em andamento'
        atualizar_chamados_estado(chamados_novos, 'Em andamento')

    # Obter todos os chamados em estado 'Em andamento' do usuário
    chamados_andamento = Chamado.objects.filter(usuario=request.user, estado='Em andamento')

    # Verificar se há mais de 5 chamados em estado 'Em andamento'
    if chamados_andamento.count() >= 5:
        # Atualizar os 5 chamados mais antigos para estado 'Finalizados'
        atualizar_chamados_estado(chamados_andamento, 'Finalizados')

    # Redirecionar de volta para o painel de chamados
    return redirect(reverse('dashboard_chamados'))

sysapp/templates/abrir_chamados.html
{% extends 'base.html' %}

{% block content %}
<style>
    body {
        font-family: Arial, sans-serif;
    }

    h2{
        margin-top: 50px;
        margin-bottom: 2.5rem;
        margin-left: -166px;
        padding-top: 20px;
    }

    .bg-custom {
        padding: -15px;
        margin-top: 1rem;
        width: 80%;
        margin: auto;
        padding-left: 150px;
        
    }
    
    .container-chamado{
        border: 1px solid #ddd;
        padding-top: 20px;
        margin-bottom: 10rem;
        max-width: 100%;
        
    }
    
    .buttons-container{
        margin-top: -9rem;
        padding-bottom: 80px;
    }
    #exampleFormControlInput1 {
        padding: 2px;
    }
</style>

<div class="bg-custom">
    <h2 class="">Abrir Chamado</h2>
    <div class="container-chamado">
        <div class="row">
            <div class="col-md-6 offset-md-1">
                <form id="chamadoForm" method="post" enctype="multipart/form-data" action="{% url 'abrir_chamados' %}">
                    {% csrf_token %}
        
                    <div class="mb-3 row align-items-center">
                        <label for="id_tipo" class="col-sm-2 col-form-label">Tipo:</label>
                        <div class="col-sm-10">
                            <select id="id_tipo" name="tipo">
                                <option selected>Selecione</option>
                                <option value="Suporte">Suporte</option>
                                <option value="Financeiro">Financeiro</option>
                                <option value="Outros">Outros</option>
                            </select>
                        </div>
                    </div>
                    <div class="mb-3 row align-items-center">
                        <label for="id_categoria" class="col-sm-2 col-form-label">Categoria:</label>
                        <div class="col-sm-10">
                            <select id="id_categoria" name="categoria" >
                                <option selected>Selecione</option>
                                <option value="Informática">Informática</option>
                                <option value="Redes">Redes</option>
                                <option value="Segurança">Segurança</option>
                            </select>
                        </div>
                    </div>
                    <div class="mb-3 row align-items-center">
                        <label for="id_titulo" class="col-sm-2 col-form-label">Título:</label>
                        <div class="col-sm-10">
                            <input type="text" id="id_titulo" name="titulo"  placeholder="Título do chamado">
                        </div>
                    </div>
                    <div class="mb-3 row align-items-left">
                        <label for="id_descricao" class="col-sm-2 col-form-label">Descrição:</label>
                        <div class="col-sm-10">
                            <textarea id="id_descricao" name="descricao" class="form-control custom-form-control" rows="8"  placeholder="Descrição do chamado" style="width: 100%;"></textarea>
                        </div>
                    </div>
                    <div class="mb-3 row align-items-center">
                        <label for="id_prioridade" class="col-sm-2">Prioridade: </label>
                        <div class="col-sm-10">
                            <select id="id_prioridade" name="prioridade"  aria-label="Default select example">
                                <option selected>Selecione</option>
                                <option value="Baixa">Baixa</option>
                                <option value="Média">Média</option>
                                <option value="Alta">Alta</option>
                            </select>
                        </div>
                    </div>

                    <div class="mb-3 row align-items-center">
                        <label for="id_anexo" class="col-sm-2 col-form-label">Anexar:</label>
                        <div class="col-sm-10">
                            <div class="input-group">
                                <label class="input-group-btn">
                                    <span class="btn btn-secondary">
                                       Incluir Anexo <input type="file" id="id_anexo" name="anexo" style="display: none;">
                                    </span>
                                </label>
                                <span class="form-text mx-3">(Tamanho máximo: 5 MB)</span>
                            </div>
                        </div>
                    </div>
                    
                </form>
               
                <div class="modal fade" id="previewModal" tabindex="-1" aria-labelledby="previewModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="previewModalLabel">Pré-visualização do Chamado</h5>
                            </div>
                            <div class="modal-body">
                                <!-- Aqui você pode exibir os detalhes do chamado pré-visualizado -->
                                <p><strong>Código:</strong> <span id="previewCodigo"></span></p>
                                <p><strong>Tipo:</strong> <span id="previewTipo"></span></p>
                                <p><strong>Categoria:</strong> <span id="previewCategoria"></span></p>
                                <p><strong>Título:</strong> <span id="previewTitulo"></span></p>
                                <p><strong>Descrição:</strong> <span id="previewDescricao"></span></p>
                                <p><strong>Prioridade:</strong> <span id="previewPrioridade"></span></p>
                                <p><strong>Anexo:</strong> <a href="#" id="previewAnexoLink" target="_blank">Abrir anexo</a></p>
                                <!-- Adicione mais campos conforme necessário -->
                
                            </div>
                            <div class="modal-footer">
                                <button type="button" id="btn-close" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="buttons-container">
        <div class="mb-3 row" id="botoes-section">
            <div class="col-sm-12">
                <button type="submit" class="btn btn-primary" id="criarChamadoBtn">Criar chamado</button>
                <a href="#" id="previewLink" data-bs-toggle="modal" data-bs-target="#previewModal">
                    Pré-visualizar
                </a>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js"></script>
    <script>
        document.getElementById('previewLink').addEventListener('click', function () {
        // Atualize os campos do modal com os valores do formulário
        document.getElementById('previewTipo').innerText = document.getElementById('id_tipo').value;
        document.getElementById('previewCategoria').innerText = document.getElementById('id_categoria').value;
        document.getElementById('previewTitulo').innerText = document.getElementById('id_titulo').value;
        document.getElementById('previewDescricao').innerText = document.getElementById('id_descricao').value;
        document.getElementById('previewPrioridade').innerText = document.getElementById('id_prioridade').value;

        // Atualiza o link de anexo com o nome do arquivo e URL
        var anexoInput = document.getElementById('id_anexo');
        var anexoName = anexoInput.files.length > 0 ? anexoInput.files[0].name : 'Nenhum anexo';
        var anexoURL = URL.createObjectURL(anexoInput.files[0]);
        var anexoLink = document.getElementById('previewAnexoLink');
        anexoLink.innerText = 'Abrir anexo: ' + anexoName;
        anexoLink.href = anexoURL;

        // Abre o modal
        var previewModal = new bootstrap.Modal(document.getElementById('previewModal'));
        previewModal.show();


        });

        document.getElementById('btn-close').addEventListener('click', function () {
        // Fecha o modal
            var previewModal = bootstrap.Modal.getInstance(document.getElementById('previewModal'));
            previewModal.hide();
        });
        
        document.getElementById('criarChamadoBtn').addEventListener('click', function () {
        // Aciona o envio do formulário quando o botão é clicado
        document.getElementById('chamadoForm').submit();
       });

    </script>
</div>
{% endblock %}

sysapp/templates/base.html
<!-- base.html -->
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Adicione o link para o CSS do Bootstrap 5 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <title>SGCShelp</title>
    <!--Link de css padrão-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <!-- Barra de Navegação -->
   <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container-fluid">
            <!-- Logo -->
            <a class="navbar-brand" href="#">
                <!--<img src="{% static 'caminho/para/seu/logo.png' %}" alt="Logo" height="30">-->
            </a>

            <!-- Botão de colapso para telas pequenas -->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Links à Direita -->
            <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Chamados</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Treinamento</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Sobre</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Contato</a>
                    </li>
                     <!-- Verifica se o usuário está autenticado -->
                     {% if user.is_authenticated %}
                     <li class="nav-item">
                         <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                     </li>
                 {% endif %}
                </ul>
            </div>
        </div>
   </nav>
 
    {% block content %}
      
    {% endblock %} 
    
    <!-- Rodapé Fixo -->
    <footer class="fixed-footer">
        <hr>
        <div class="icon-social">
            <p>Acompanhe-nos</p>
            <a href="#" class="icon-facebook"><i class="fab fa-facebook-f"></i></a>
            <a href="#" class="icon-instagram"><i class="fab fa-instagram"></i></a>
            <a href="#" class="icon-twitter"><i class="fab fa-twitter"></i></a>
            <a href="#" class="icon-youtube"><i class="fab fa-youtube"></i></a>
            <a href="#" class="icon-linkedin"><i class="fab fa-linkedin-in"></i></a>
        </div>
        <p class="direitos">© SGCShelp Developed by Pedro Araújo</p>
    </footer>    
</body>
</html>

sysapp/templates/cadastrar_usuario.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Cadastro de Usuário{% endblock %}

{% block content %}

{% if messages %}
    <div class="alert alert-success" role="alert">
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    </div>
{% endif %}
<div class="container ">
    <h2 class="text-left mt-5">Cadastro</h2>

    <form method="post" action="{% url 'cadastrar_usuario' %}"  id="form" class="mt-3" onsubmit="return validarCadastro()">
        {% csrf_token %}

        <div class="row mb-6">
            <div class="col-md-6">
                <label for="{{ form.nome.id }}" class="">Nome:</label>
                {{ form.nome }}
            </div>

            <div class="col-md-6">
                <label for="{{ form.sobrenome.id }}" class="">Sobrenome:</label>
                {{ form.sobrenome }}
            </div>
        </div>

        <div class="mb-6" >
            <label for="{{ form.email.id }}" class="">E-mail:</label>
            {{ form.email }}
           
        </div>

        <div class="mb-6">
            <label for="{{ form.nome_usuario.id }}" class="">Nome de Usuário:</label>
            {{ form.nome_usuario }}
        </div>

        <div class="mb-2">
            <label for="{{ form.password.id }}" class="">Senha:</label>
            {{ form.password }}
        </div>
        
        <div class="mb-2">
            <div>
                <span class="">Sou:</span>
                {% for value, label in form.tipo_usuario.field.choices %}
                    <label class="radio-inline" for="{{ form.tipo_usuario.id }}_{{ value }}">
                        <input type="radio" id="{{ form.tipo_usuario.id }}_{{ value }}" name="{{ form.tipo_usuario.name }}" value="{{ value }}"
                            {% if form.tipo_usuario.value == value %}checked{% endif %}>
                        {{ label }}
                    </label>
                {% endfor %}
            </div>
        </div>
        

        <div class="" id="matricula-field">
            <label for="{{ form.matricula.id }}" class="form-label"></label>
            {{ form.matricula }}
        </div>

        <br>

        <div class="d-flex justify-content-center">
            <button type="submit" id="btn-cadastro" class="btn btn-primary">Finalizar cadastro</button>
        </div>
    </form>

      <!-- Adicione o link para a página de login -->
      <p class=" text-center mt-3">Já possui uma conta? <a href="{% url 'fazer_login' %}">Faça login aqui</a>.</p>

    <!-- Scripts JavaScript -->
    <script>
        function validarCadastro() {
            var form = document.getElementById('form');
            var isValid = true;
    
            // Função para validar o formato do e-mail
            function isValidEmail(email) {
                var emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
                return emailRegex.test(email);
            }
    
            // Validar cada campo individualmente
            var nome = form.querySelector('#id_nome').value.trim();
            var sobrenome = form.querySelector('#id_sobrenome').value.trim();
            var email = form.querySelector('#id_email').value.trim();
            var nomeUsuario = form.querySelector('#id_nome_usuario').value.trim();
            var senha = form.querySelector('#id_password').value.trim();
            var matricula = form.querySelector('#id_matricula').value.trim();
    
            // Validar Nome
            if (nome === '') {
                isValid = false;
                alert('Campo Nome é obrigatório.');
            }
    
            // Validar Sobrenome
            if (sobrenome === '') {
                isValid = false;
                alert('Campo Sobrenome é obrigatório.');
            }
    
            // Validar E-mail
            if (email === '' || !isValidEmail(email)) {
                isValid = false;
                alert('Campo E-mail é obrigatório e deve ser um e-mail válido.');
            }
    
            // Validar Nome de Usuário
            if (nomeUsuario === '') {
                isValid = false;
                alert('Campo Nome de Usuário é obrigatório.');
            }
    
            // Validar Senha
            if (senha === '' || senha.length < 8) {
                isValid = false;
                alert('A senha deve ter pelo menos 8 caracteres.');
            }
    
            // Validar Matrícula
            if (matricula === '') {
                isValid = false;
                alert('Campo Matrícula é obrigatório.');
            }
    
            // Retornar false para impedir a submissão do formulário se houver erros
            return isValid;
        }


        document.addEventListener("DOMContentLoaded", function() {
        var matriculaField = document.getElementById('matricula-field');
        var matriculaInput = document.getElementById('id_matricula');

        document.querySelectorAll('input[name="{{ form.tipo_usuario.name }}"]').forEach(function(input) {
            input.addEventListener('change', function() {
                if (this.value === 'Aluno') {
                    matriculaField.style.display = 'block';
                    matriculaInput.setAttribute('placeholder', 'Matrícula');
                } else if (this.value === 'Servidor') {
                    matriculaField.style.display = 'block';
                    matriculaInput.setAttribute('placeholder', 'Siape');
                } else {
                    matriculaField.style.display = 'none';
                }
            });
        });
    });
    </script>

    

</div>
{% endblock %}